#!/bin/sh

# Show three months in a small terminal popup.

exec st -c SlstatusPopup -n slstatus-calendar -t "Calendar" \
	-f "NotoSans Nerd Font:size=10" -g "68x10" \
	-e sh -c 'cal -3; exec tail -f /dev/null'
